### ISSUE TITLE
Directive does not work with two addresses in the same form

### ISSUE THREAD

**Issue by arthurfrancioni** [cesarbarone/angular-viacep#2]
Directive does not work with two addresses in the same form

![cep](https://cloud.githubusercontent.com/assets/1223383/19806152/9d20d7ac-9cf7-11e6-8150-b7a2a216b6e0.png)

**Comment by cesarbarone** [comment]
Issue resolved at: https://github.com/cesarbarone/angular-viacep/tree/1.1.2

**Comment by cesarbarone** [comment]
@arthurfrancioni Don't forget to check the plunker, i changed the implementation and you need to refactor your code.

https://plnkr.co/edit/2YkyutxNKrm99jRENNwt?p=preview
